name: Secret Scan

on:
  push:
    branches: ["main", "master", "develop"]
  pull_request:
    branches: ["main", "master", "develop"]

jobs:
  secret-scan:
    name: Scan repository for secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # remove secret scanning for now.
      # - name: Run secret scanner
      #   run: |
      #     chmod +x .github/scripts/check-secrets.sh || true
      #     .github/scripts/check-secrets.sh
